### PR TITLE
feat: basic typing's

### PR DESCRIPTION
**Pull request by Wilbert-mad**
Integrate basic typing's for the package.
Update package.json to register the `index.d.ts` file.

### CODE REVIEW

**Comment by FlaringPhoenix** [comment]
Thank you! I was planning on doing this but you got to it first.

**Comment by Wilbert-mad** [comment]
Oh sorry... 👀

**Comment by FlaringPhoenix** [comment]
No need to apologize. I am happy that you did this lol. Thanks for helping out.

**Comment by Wilbert-mad** [comment]
oh ya no problem, and thank you for the hosting 👍 :)

**Comment by FlaringPhoenix** [comment]
Anytime! Just curious, what's your discord username?

**Comment by Wilbert-mad** [comment]
Xa_puppet#2393

**Pull request merged**
